version: "2"

services:
  php-composer:
    build: ./php-composer
    working_dir: /var/www
    ports:
      - "9001:9001"
    volumes:
      - ../..:/var/www
    environment:
      COMPOSER_HOME: /tmp
